// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyB08zheG-9FgBSl3QxHDOrVsBZ52yfsk5s",
    authDomain: "carcheks-227d4.firebaseapp.com",
    projectId: "carcheks-227d4",
    storageBucket: "carcheks-227d4.firebasestorage.app",
    messagingSenderId: "424737096430",
    appId: "1:424737096430:android:3501ea08d592239b8829ff",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyB08zheG-9FgBSl3QxHDOrVsBZ52yfsk5s",
    appId: "1:424737096430:android:3501ea08d592239b8829ff",
    messagingSenderId: '424737096430',
    projectId: 'carcheks-227d4',
    storageBucket: 'carcheks-227d4.firebasestorage.app',
    iosBundleId: 'com.napesoft.carcheks',
  );
}
